### ISSUE TITLE
dcc-ops/redwood compatibility (new redwood-client)

### ISSUE THREAD

**Issue by benjaminran** [BD2KGenomics/dcc-action-service#7]
AlignmentQCTask[V2] uses the old client to do redwood upload/download [and list metadata entities]. The decider dockerfile can be changed to inherit from [dcc-redwod-client](https://github.com/BD2KGenomics/dcc-redwood-client), then the `dcc-metadata-client` and `dcc-storage-client` commands can be assumed. This'll decouple the code for all future updates and the action-service admin won't have to worry about making code changes when the redwood-client is updated (just change the base image tag number).

Also, to list the dcc-ops metadata server entities, you should use _https://metadata.${redwood_endpoint}/entities_ (port 8444 is no longer exposed.

**Comment by caaespin** [comment]
Done in the latest release.
